language: scala
scala:
  - 2.11.8
jdk:
  - oraclejdk8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
script:
  - pushd tests/c-snippets && make CC=gcc-6 && popd
  - sbt compile
  - sbt test

# vim: ts=2 sw=2 sts=2
